# Generated by Django 5.2 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_add_perf_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "match",
                    models.CharField(blank=True, max_length=256, verbose_name="match"),
                ),
                (
                    "matching_algorithm",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Any word"),
                            (2, "All words"),
                            (3, "Exact match"),
                            (4, "Regular expression"),
                            (5, "Fuzzy word"),
                            (6, "Automatic"),
                        ],
                        default=1,
                        verbose_name="matching algorithm",
                    ),
                ),
                (
                    "is_insensitive",
                    models.BooleanField(default=True, verbose_name="is insensitive"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "cabinet",
                "verbose_name_plural": "cabinets",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="cabinet",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"),
                name="documents_cabinet_unique_name_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="cabinet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("name",),
                name="documents_cabinet_name_uniq",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="cabinet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.cabinet",
                verbose_name="cabinet",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="inherit_cabinet_permissions",
            field=models.BooleanField(
                default=True,
                help_text="Use the cabinet's view and change permissions instead of the document's permissions.",
                verbose_name="inherit cabinet permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["cabinet", "created"],
                name="documents_d_cabinet_8e32c8_idx",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_cabinet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.cabinet",
                verbose_name="belongs to this cabinet",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_cabinets",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_cabinet",
                to="documents.cabinet",
                verbose_name="belongs to one of these cabinets",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_not_cabinets",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_not_cabinet",
                to="documents.cabinet",
                verbose_name="does not belong to these cabinet(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="assign_cabinet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.cabinet",
                verbose_name="assign this cabinet",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="assign_inherit_cabinet_permissions",
            field=models.BooleanField(
                default=True,
                verbose_name="inherit permissions from the assigned cabinet",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="remove_cabinets",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="documents.cabinet",
                verbose_name="remove these cabinet(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="remove_all_cabinets",
            field=models.BooleanField(
                default=False,
                verbose_name="remove all cabinets",
            ),
        ),
        migrations.AlterField(
            model_name="savedviewfilterrule",
            name="rule_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "title contains"),
                    (1, "content contains"),
                    (2, "ASN is"),
                    (3, "correspondent is"),
                    (4, "document type is"),
                    (5, "is in inbox"),
                    (6, "has tag"),
                    (7, "has any tag"),
                    (8, "created before"),
                    (9, "created after"),
                    (10, "created year is"),
                    (11, "created month is"),
                    (12, "created day is"),
                    (13, "added before"),
                    (14, "added after"),
                    (15, "modified before"),
                    (16, "modified after"),
                    (17, "does not have tag"),
                    (18, "does not have ASN"),
                    (19, "title or content contains"),
                    (20, "fulltext query"),
                    (21, "more like this"),
                    (22, "has tags in"),
                    (23, "ASN greater than"),
                    (24, "ASN less than"),
                    (25, "storage path is"),
                    (26, "has correspondent in"),
                    (27, "does not have correspondent in"),
                    (28, "has document type in"),
                    (29, "does not have document type in"),
                    (30, "has storage path in"),
                    (31, "does not have storage path in"),
                    (32, "owner is"),
                    (33, "has owner in"),
                    (34, "does not have owner"),
                    (35, "does not have owner in"),
                    (36, "has custom field value"),
                    (37, "is shared by me"),
                    (38, "has custom fields"),
                    (39, "has custom field in"),
                    (40, "does not have custom field in"),
                    (41, "does not have custom field"),
                    (42, "custom fields query"),
                    (43, "created to"),
                    (44, "created from"),
                    (45, "added to"),
                    (46, "added from"),
                    (47, "mime type is"),
                    (48, "simple title search"),
                    (49, "simple text search"),
                    (50, "cabinet is"),
                    (51, "has cabinet in"),
                    (52, "does not have cabinet in"),
                ],
                verbose_name="rule type",
            ),
        ),
    ]
