# Generated by Django 5.2.16 on 2026-08-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0023_cabinets"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_cabinet_068e6f_idx",
            old_name="documents_d_cabinet_8e32c8_idx",
        ),
    ]
